// Heroicons 2.2.0, 16/solid/minus.svg (MIT, Tailwind Labs: https://heroicons.com).
// Generated by scripts/icons.mjs; don't edit.
import IconProps from '../icon.types';

export default function MinusMicro(props: IconProps) {
    return (
        <svg
            className="size-4"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 16 16"
            fill="currentColor"
            aria-hidden="true"
            data-slot="icon"
            {...props}
        >
            <path d="M3.75 7.25a.75.75 0 0 0 0 1.5h8.5a.75.75 0 0 0 0-1.5h-8.5Z" />
        </svg>
    );
}
