// Writes packages/icons (used by Zen's components and docs, not exported) from Heroicons (a pinned dev dependency), so every icon is
// Heroicons' own SVG, unchanged but for JSX attribute names. Run: node scripts/icons.mjs
// Sets: 24/outline for icons drawn at 20px and up; 16/solid (Heroicons' "micro" set,
// drawn for 16px) for the small glyphs inside components.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';

const require = createRequire(import.meta.url);
const heroicons = dirname(require.resolve('heroicons/package.json'));
const { version } = JSON.parse(readFileSync(join(heroicons, 'package.json'), 'utf8'));

// file (under packages/icons): [component, Heroicons source]
const ICONS = {
    'arrow-left': ['ArrowLeft', '24/outline/arrow-left'],
    'arrow-right': ['ArrowRight', '24/outline/arrow-right'],
    bars: ['Bars', '24/outline/bars-3'],
    calendar: ['CalendarIcon', '24/outline/calendar'],
    'chart-bar': ['ChartBarIcon', '24/outline/chart-bar'],
    'chevron-down': ['ChevronDown', '24/outline/chevron-down'],
    'chevron-left': ['ChevronLeft', '24/outline/chevron-left'],
    'chevron-right': ['ChevronRight', '24/outline/chevron-right'],
    'chevron-up': ['ChevronUp', '24/outline/chevron-up'],
    ellipsis: ['Ellipsis', '16/solid/ellipsis-horizontal'],
    flag: ['Flag', '24/outline/flag'],
    'list-bullet': ['ListBullet', '24/outline/list-bullet'],
    lock: ['Lock', '24/outline/lock-closed'],
    logout: ['Logout', '24/outline/arrow-right-start-on-rectangle'],
    search: ['Search', '24/outline/magnifying-glass'],
    settings: ['Settings', '24/outline/cog-6-tooth'],
    squares: ['Squares', '24/outline/squares-2x2'],
    table: ['TableIcon', '24/outline/table-cells'],
    'x-mark': ['XMark', '24/outline/x-mark'],
    // The small glyphs components draw themselves (not exported from the package).
    'micro/arrow-trending-down': ['ArrowTrendingDownMicro', '16/solid/arrow-trending-down'],
    'micro/arrow-trending-up': ['ArrowTrendingUpMicro', '16/solid/arrow-trending-up'],
    'micro/calendar': ['CalendarMicro', '16/solid/calendar'],
    'micro/check': ['CheckMicro', '16/solid/check'],
    'micro/chevron-down': ['ChevronDownMicro', '16/solid/chevron-down'],
    'micro/chevron-right': ['ChevronRightMicro', '16/solid/chevron-right'],
    'micro/exclamation-triangle': ['ExclamationTriangleMicro', '16/solid/exclamation-triangle'],
    'micro/information-circle': ['InformationCircleMicro', '16/solid/information-circle'],
    'micro/minus': ['MinusMicro', '16/solid/minus'],
    'micro/moon': ['MoonMicro', '16/solid/moon'],
    'micro/sun': ['SunMicro', '16/solid/sun'],
    'micro/x-mark': ['XMarkMicro', '16/solid/x-mark'],
};

const ATTRS = {
    'stroke-width': 'strokeWidth',
    'stroke-linecap': 'strokeLinecap',
    'stroke-linejoin': 'strokeLinejoin',
    'fill-rule': 'fillRule',
    'clip-rule': 'clipRule',
};

for (const [file, [name, source]] of Object.entries(ICONS)) {
    let svg = readFileSync(join(heroicons, `${source}.svg`), 'utf8').trim();
    for (const [from, to] of Object.entries(ATTRS)) svg = svg.replaceAll(`${from}=`, `${to}=`);
    // Sized by default as Heroicons are drawn (24 or 16px); the caller's props (className too) go on top.
    const size = source.startsWith('16/') ? 'size-4' : 'size-6';
    svg = svg.replace(/^<svg /, `<svg className="${size}" `).replace(/>/, ' {...props}>');
    const depth = file.includes('/') ? '../' : './';
    const code = `// Heroicons ${version}, ${source}.svg (MIT, Tailwind Labs: https://heroicons.com).
// Generated by scripts/icons.mjs; don't edit.
import IconProps from '${depth}icon.types';

export default function ${name}(props: IconProps) {
    return (${svg});
}
`;
    mkdirSync(dirname(`packages/icons/${file}.tsx`), { recursive: true });
    writeFileSync(`packages/icons/${file}.tsx`, code);
}
execFileSync('vp', ['fmt', 'packages/icons'], { stdio: 'inherit' });
