// Heroicons 2.2.0, 24/outline/arrow-left.svg (MIT, Tailwind Labs: https://heroicons.com).
// Generated by scripts/icons.mjs; don't edit.
import IconProps from './icon.types';

export default function ArrowLeft(props: IconProps) {
    return (
        <svg
            className="size-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth="1.5"
            stroke="currentColor"
            aria-hidden="true"
            data-slot="icon"
            {...props}
        >
            <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
        </svg>
    );
}
