// Heroicons 2.2.0, 24/outline/arrow-right-start-on-rectangle.svg (MIT, Tailwind Labs: https://heroicons.com).
// Generated by scripts/icons.mjs; don't edit.
import IconProps from './icon.types';

export default function Logout(props: IconProps) {
    return (
        <svg
            className="size-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth="1.5"
            stroke="currentColor"
            aria-hidden="true"
            data-slot="icon"
            {...props}
        >
            <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15m3 0 3-3m0 0-3-3m3 3H9"
            />
        </svg>
    );
}
