// Heroicons 2.2.0, 24/outline/magnifying-glass.svg (MIT, Tailwind Labs: https://heroicons.com).
// Generated by scripts/icons.mjs; don't edit.
import IconProps from './icon.types';

export default function Search(props: IconProps) {
    return (
        <svg
            className="size-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth="1.5"
            stroke="currentColor"
            aria-hidden="true"
            data-slot="icon"
            {...props}
        >
            <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
            />
        </svg>
    );
}
